pipeline {
	agent any
	 triggers {
        cron('* * * * *')
    }
	stages {
		stage('build') {
			when {
            triggeredBy 'user'
            } 
			steps {
				
                    echo 'build the job'
                
			}
		}
		stage('script') {
			when {
            triggeredBy 'user'
            } 
			steps {
				
                    echo 'script triggered manually'
                  
			}
		}
		stage('timerscript') {
		when {
            triggeredBy 'TimerTrigger'
            } 
			steps {
				
                    echo 'Timmer triggered the script'
                
			}
		}
    }
}
