pipeline {

    agent any

    stages {

        stage('Test') {

            steps {

                script {

                    echo 'this is for the testing purpose'

                    echo 'testing completed'

                }

            }

        }

    }

}
